### ISSUE TITLE
Duplicate navbars

### ISSUE THREAD

**Issue by mrhosier42** [Team-Chem/LCCC#7]
Need to have a singular unified navbar that will be accessible to every page, will need to load partial navbars when:
*  A user is logged in or signed out.,
*  If the logged in user is an admin (optional if we want extended features.

**Comment by TrashDeviance** [comment]
This issue has been fixed for all of the pages. The reason how to do with something in the body of the main styles.css file that was making the navbar not completely at the top of the page.
